### ISSUE TITLE
Refresh/Update problem

### ISSUE THREAD

**Issue by pos42** [krakan/micronomy#34]
When adding hours to the sheet and pressing "save" I can see the rows "Saldo" and "Fakturerbart" aren't updated. For those rows to get updated I had to refresh the browser. I expected those rows to update when I press save on the time sheet.

Feature or bug?

(Using Safari on macOS Big Sur 11.1)

Update:
Can see now that it works with chrome. Also it seems it works with Safari when trying again (after the first browser refresh). I maybe was/is a refresh issue with Safari. Now the rows "Saldo" and "Fakturerbart" update when pressing "save". Will keep my eyes of it onwards. So this was maybe a false alarm. Should perhaps have waited a little to file a report :)

**Comment by krakan** [comment]
Thanks for the bug report!
I believe this too is due to lacking error handling - every save results in multiple calls to the API, the last of which would update the view - so if the last one fails the database is updated but the view will be wrong. In theory the POST should then end up in a waiting state but I've seen that this doesn't always happen. It would be really weird if it was browser dependent.
The solution is to better handle when the API is flaky.

**Comment by krakan** [comment]
A fix is implemented but not yet deployed to micronomy.init.se.
