### ISSUE TITLE
Rows selected for "Denna vecka" carry over to next week in broken format

### ISSUE THREAD

**Issue by aiqueneldar** [krakan/micronomy#52]
Rows selected for just one particular week carry over in an broken state to the next week if you edit a previous week and then go to current week.
Steps to reproduce:
Use time report from last week that isn't turned in yet. Create new a new reporting row.
For example select "Frånvaro - Init DevOps / Sjukdom hel dag" and set it to "Denna vecka". 
Then save and deliver the weekly time report ("Spare" followed by "Avlämna").
Then click "Idag" to change to the current week.
The old "Frånvaro - Init DevOps / Sjukdom hel dag" row is still there, but only as "Frånvaro - Init DevOps" without proper specification. 

I've noticed a variant of this where I can have a row in time report view that looks complete and fine. But when I try and use "Avlämna" I get an error that no task has been selected for that row. Then if I go to "Redigera rader" I see that the row in fact does miss it's task. I'm not completely sure when it happens, but it might happen if I add a row permantntly ("Tills vidare"), but doesn't fill in any time during that week. But I haven't actually discovered a certain pattern for this one.

**Comment by krakan** [comment]
Yes, I get that too ... but haven't been bothered enough to fix it yet ...
But it needs to be fixed.

**Comment by krakan** [comment]
It turns out you're not allowed to combine changing the task and the permanence in the same API call ... This can actually be observed in the Maconomy interface too - if you change the task without saving and the click the permanence checkbox, the task change is lost. Apparently a bug in the backend code that has to be solved in the frontend. :man_facepalming:
